export const START_APPLICATION = 'START_APPLICATION';
export const CONFIG_LOADED = 'CONFIG_LOADED';
export const SEARCH_CONDITION_TRIGGER = 'SEARCH_CONDITION_TRIGGER';
export const SET_MODE = 'SET_MODE';
export const SELECT_EXP_TRIGGER = 'SELECT_EXP_TRIGGER';
export const SET_VIEW_MODE = 'SET_VIEW_MODE';